# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import swarm_pb2 as swarm__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swarm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamActions = channel.stream_stream(
                '/swarm.BrainService/StreamActions',
                request_serializer=swarm__pb2.Observation.SerializeToString,
                response_deserializer=swarm__pb2.Action.FromString,
                _registered_method=True)


class BrainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamActions(self, request_iterator, context):
        """Unary yerine çift yönlü akış (Bidirectional Streaming) kullanıyoruz.
        Bu sayede TCP el sıkışma maliyetinden kurtulup, saniyede yüzlerce 
        paketi gecikmesiz iletebiliriz.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamActions': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamActions,
                    request_deserializer=swarm__pb2.Observation.FromString,
                    response_serializer=swarm__pb2.Action.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swarm.BrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swarm.BrainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamActions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/swarm.BrainService/StreamActions',
            swarm__pb2.Observation.SerializeToString,
            swarm__pb2.Action.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
