# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swarm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swarm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bswarm.proto\x12\x05swarm\"\xfb\x01\n\x0bObservation\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x12\n\nblock_grid\x18\x02 \x03(\x05\x12\x0e\n\x06health\x18\x03 \x01(\x02\x12\x0e\n\x06hunger\x18\x04 \x01(\x02\x12\x12\n\nposition_x\x18\x05 \x01(\x01\x12\x12\n\nposition_y\x18\x06 \x01(\x01\x12\x12\n\nposition_z\x18\x07 \x01(\x01\x12\x1f\n\x08\x65ntities\x18\x08 \x03(\x0b\x32\r.swarm.Entity\x12\x17\n\x0f\x64ost_bana_vurdu\x18\t \x01(\x08\x12\x16\n\x0evuran_dost_yaw\x18\n \x01(\x02\x12\x18\n\x10vuran_dost_pitch\x18\x0b \x01(\x02\"p\n\x06\x45ntity\x12\x11\n\tentity_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x65ntity_type\x18\x02 \x01(\x05\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\x12\x14\n\x0crelative_yaw\x18\x04 \x01(\x02\x12\x16\n\x0erelative_pitch\x18\x05 \x01(\x02\"Z\n\x06\x41\x63tion\x12\x13\n\x0bkey_bitmask\x18\x01 \x01(\r\x12\x13\n\x0bselect_slot\x18\x02 \x01(\x05\x12\x11\n\tdelta_yaw\x18\x03 \x01(\x02\x12\x13\n\x0b\x64\x65lta_pitch\x18\x04 \x01(\x02\x32\x46\n\x0c\x42rainService\x12\x36\n\rStreamActions\x12\x12.swarm.Observation\x1a\r.swarm.Action(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swarm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBSERVATION']._serialized_start=23
  _globals['_OBSERVATION']._serialized_end=274
  _globals['_ENTITY']._serialized_start=276
  _globals['_ENTITY']._serialized_end=388
  _globals['_ACTION']._serialized_start=390
  _globals['_ACTION']._serialized_end=480
  _globals['_BRAINSERVICE']._serialized_start=482
  _globals['_BRAINSERVICE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
